### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#2018]
**Please complete the following information** 
Site repository URL: https://github.com/christoph-LSN/MT_Site
Open SDG version: [2.1.1]

**Describe the bug**

If I try to make changes in my site repo the following error message is shown when github tries to deploy the site.

https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612

Run actions/deploy-pages@v2
  with:
    token: ***
    timeout: 600000
    error_count: [1](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:1)0
    reporting_interval: 5000
    artifact_name: github-pages
    preview: false
Artifact exchange URL: https://pipelines.actions.githubusercontent.com/90tUFZQH6deEYZm5WRiuNMEjgGQMoqaF8ybrfMiXd8FCyPp9r1/_apis/pipelines/workflows/544479861[2](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:2)/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/90tUFZQH6deEYZm5WRiuNMEjgGQMoqaF8ybrfMiXd8FCyPp9r1/_apis/pipelines/1/runs/1750/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "c[3](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:3)df1ac807[4](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:4)fda6[5](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:5)edd7b5895b872e7114802081",
	"oidc_token": "***"
}
Created deployment for c3df1ac8074fda[6](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:6)5edd[7](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:7)b5[8](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:8)[9](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:10)5b872e7[11](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:12)4802081, ID: c3df1ac8074fda65edd7b5895b872e71[14](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:15)802081
Getting Pages deployment status...
Current status: deployment_in_progress
Getting Pages deployment status...
Current status: deployment_in_progress
Getting Pages deployment status...
Current status: updating_pages
Getting Pages deployment status...
Current status: updating_pages
Getting Pages deployment status...
Current status: updating_pages
Getting Pages deployment status...
Current status: updating_pages
Getting Pages deployment status...
Current status: updating_pages
Getting Pages deployment status...
Error: Getting Pages deployment status failed
Error: HttpError: Server Error
    at /home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getPagesDeploymentStatus (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:144:1)
    at Deployment.check (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:[16](https://github.com/christoph-LSN/MT_Site/actions/runs/5444798612/jobs/9903166750#step:2:17)4:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:40:1)
Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle

any ideas @brockfanning @sarah-beasley @MoBosse ?

**Comment by christoph-LSN** [comment]
@brockfanning @sarah-beasley @MoBosse 

Somteimes waiting an hour solves the problem....

I leave this issue open perhaps someone has the same deploy error
